# Konfigurasi GitHub Actions untuk CI/CD
name: IaC Security Audit
on: [push, pull_request]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          pip install -r requirements.txt
          curl -sSL https://get.snyk.io | bash
      - name: Run Audit
        run: python src/audit_iac.py --path tests/sample_files --format json > reports/audit_report.json
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: reports/audit_report.json
